const SERVICES = [
  {
    id: '1',
    img: 'yape.png',
    option: 'Yape Fake',
    message: [
      '🚀 *YAPE FAKE - 2026*',
      '',
      'Activa tu licencia de forma segura aquí.',
      '💰 *Precio:* S/ 40',
      '',
      '✅ *Pago único*',
      '✅ *Acceso permanente*',
      '✅ *Actualizaciones automáticas*',
      '',
      'Si deseas adquirirlo, escribe: `/pagar`',
    ],
  },
  {
    id: '2',
    img: 'banks.png',
    option: 'Bancas Fake',
    message: [
      '🚀 *BANCAS FAKE*',
      '',
      'Activa el acceso a tus bancas.',
      'No necesitas reinstalar la app: el acceso es directamente desde tu mismo Yape.',
      '',
      '💰 *Precios:*',
      '• 1 App → S/ 15',
      '• 2 Apps → S/ 25',
      '• 3 Apps → S/ 30',
      '',
      '✅ *Pago único*',
      '✅ *Activación inmediata*',
      '✅ *Actualizaciones automáticas*',
      '',
      'Si deseas adquirirlo, escribe: `/pagar',
    ],
  },
  {
    id: '3',
    img: 'vip.png',
    option: 'Contenido VIP',
    message: [
      '🔞 *GRUPO VIP CONTENIDO PREMIUM*',
      '',
      'Accede al grupo privado con contenido exclusivo.',
      'Encontrarás material de influencers, tiktokers peruanas, castings y contenido casero.',
      '',
      '💰 *Precio:* S/ 50',
      '',
      '✅ Pago único',
      '✅ Acceso permanente',
      '✅ Fotos y videos exclusivos',
      '✅ Contenido nuevo constantemente',
      '✅ Descarga todo el material',
      '',
      'Si deseas adquirirlo ,escribe: `/pagar`',
    ],
  },
  {
    id: '4',
    img: 'followers.png',
    option: 'Seguidores',
    message: [
      '🚀 *SEGUIDORES PARA REDES SOCIALES*',
      '',
      '💯 Impulsa tu perfil y aumenta tu alcance.',
      '',
      '✅ *Entrega inmediata*',
      '✅ *Tiempo de servicio:* 5 a 30 minutos',
      '✅ *Sin límite de cantidad*, tú decides',
      '',
      'Si deseas solicitar un pedido',
      'escribe: `/pagar`',
    ],
  },
  {
    id: '5',
    img: 'doxing.png',
    option: 'Doxeos',
    message: [
      '🔎 *SERVICIOS DE DOXEOS*',
      '',
      'Realiza búsquedas mediante:',
      '',
      '✅ *DNI o nombres completos*',
      '✅ *Número de celular*',
      '✅ *Placa vehicular*',
      '',
      'Si deseas solicitar una consulta`',
      'escribe: `/pagar`',
    ],
  },
];
